name: "Release pipeline"
description: "Multiple actions that can be used to create releases"
inputs:
  auth_token:
    description: "Github Token"
    required: true
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "docker"
  image: "Dockerfile"
