name: "Release pipeline"
description: "Multiple actions that can be used to create releases"
inputs:
  auth_token:
    description: "Github Token"
    required: true
  repo:
    description: Name of the repo including the org/user, ie. pier-oliviert/phonebook
  variable:
    description: Name of the repository variable you want to store the version into.
  main_branch:
    description: Name of the main branch for this repo (defaults to "main")
  changelog:
    description: The changelog generated for this release
  charts:
    description: Path where the chart is located (defaults to "charts/")
  chart_yaml:
    description: Name of the Chart.yaml file (defaults to Chart.yaml)
  page_branch:
    description: Name of the branch where pages are committed (defaults to gh-pages)
  upload_url:
    description: Upload URL for the release assets
  tag:
    description: Name of the tag
  tmp_path:
    description: Location to store temporary data (defaults to "/tmp/charts")
  version:
    description: Version generated, ie. "v0.0.1" -> "0.0.1"
  commit_start:
    description: Commit SHA that was tagged with the new version (0.0.2)
  commit_end:
    description: Commit SHA tagged for the previous version (0.0.1)

outputs:
  version:
    description: Version generated, ie. "v0.0.1" -> "0.0.1"
  commit_start:
    description: Commit SHA that was tagged with the new version (0.0.2)
  commit_end:
    description: Commit SHA tagged for the previous version (0.0.1)
  changelog:
    description: The changelog generated by this action
  tag:
    description: Name of the tag
  release_id:
    description: ID of the release that was created
  release_url:
    description: URL of the release that was created
  upload_url:
    description: Upload URL for release assets
runs:
  using: "docker"
  image: "Dockerfile"
